---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3.5-jdk-8-alpine"

inputs:
- name: application-pipeline
- name: current-app-info
- name: app-manifest-info

outputs:
- name: app-manifest-output

run:
  path: application-pipeline/pipeline/tasks/build-app