---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3.5-jdk-8-alpine"

inputs:
- name: application-pipeline

run:
  path: application-pipeline/pipeline/tasks/run-unit-tests
