---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: application-pipeline
- name: current-app-info

run:
  path: application-pipeline/pipeline/tasks/update-routes
