---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: si2ci

outputs:
- name: current-app-info

run:
  path: si2ci/pipeline/tasks/create-pas-space
