#!/bin/sh

set -eu

root=$PWD

ls -ltrh
mkdir $HOME/.ssh
echo "$GITHUB_SSHKEY" > $HOME/.ssh/id_rsa
echo Clonning repo
ssh-keyscan github.com >> ~/.ssh/known_hosts
chmod 700 ~/.ssh/known_hosts
chmod 700 ~/.ssh/id_rsa
git clone git@github.com:$GITHUB_ORGNAME/$REPONAME.git
cd $REPONAME

curl https://$SPRING_INITURL/starter.tgz  \
  -d dependencies=web,actuator \
  -d language=java \
  -d bootVersion=$SI2CI_BOOTVERSION \
  -d type=maven-project \
  -o spring.tgz

tar -zxvf spring.tgz
rm spring.tgz

git config --global user.email "ubsbot@pivotal.io"
git config --global user.name "UBS BOT"
git add -A 
git commit -a -m "Added Spring Initializr content"
git push
